name: CI

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  compile:
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, macos-latest, windows-latest ]

    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v1

    - name: Dependancies (mac)
      if: runner.os == 'macOS'
      shell: bash
      run: brew install openssl@1.1

    - name: Configure
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
            SSL_OPTS="-D OPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1"
        fi
        cmake ${SSL_OPTS} -B build

    - name: Build
      shell: bash
      run: cmake --build build

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{matrix.os}}-build
        path: build
